### ISSUE TITLE
Span

### ISSUE THREAD

**Issue by Maaike0904** [r20222/server-side-rendering#11]
https://github.com/r20222/server-side-rendering/blob/9e8dbf52d5d82cf0170d98e7bf6ddc7f95c733c6/views/partials/foot.ejs#L2
Span om de copy heen om hem om te draaien

**Comment by r20222** [comment]
@Maaike0904 Ik snap niet zo goed waarom ik de copy moet omdraaien? :)

**Comment by r20222** [comment]
gefixt :)
