### ISSUE TITLE
Allergeen plaatjes

### ISSUE THREAD

**Issue by Maaike0904** [r20222/server-side-rendering#13]
<img width="362" alt="Scherm­afbeelding 2023-03-10 om 11 58 29" src="https://user-images.githubusercontent.com/112861144/224298971-99587924-0dec-4710-8cb7-9caeb196ed59.png">
<img width="373" alt="Scherm­afbeelding 2023-03-10 om 11 59 41" src="https://user-images.githubusercontent.com/112861144/224299249-f736eeff-9dfd-48ba-857c-e06d9c6f4827.png">

Plaatjes misschien iets meer naar beneden zodat het in het midden staat

**Comment by r20222** [comment]
Goed gezien! Ik heb het nu opgelost met calc() & align-self:

```CSS
    top: calc(50% - 5rem);
    align-self: center  ;
    height:10rem;
```
