### ISSUE TITLE
Pagina's beginnen met hoofdletter

### ISSUE THREAD

**Issue by Maaike0904** [r20222/server-side-rendering#2]
Ik weet niet of het handig is om je ejs pagina's te beginnen met een hoofdletter?

**Comment by r20222** [comment]
Ik heb hier hoofdletters gebruikt om het dynamisch te maken. Ik heb de verwijzing naar de linkjes dynamisch gemaakt, en omdat alle namen in de database met een hoofletter beginnen, moest ik de ejs pagina's ook met een hoofdletter laten beginnen. Het bespaard heel veel code.

```EJS
 <a class="article-a" href="/<%= category.titel %>">
```
