### ISSUE TITLE
Blokjes idee

### ISSUE THREAD

**Issue by Maaike0904** [r20222/server-side-rendering#4]
Misschien is het ook vet om zoiets te doen met blokjes, dus ipv een border een border shadow toe te voegen. 
<img width="167" alt="Scherm­afbeelding 2023-03-10 om 11 11 47" src="https://user-images.githubusercontent.com/112861144/224297516-fc39b5de-1854-4c52-b4eb-1a0a606fc25a.png">

**Comment by r20222** [comment]
Supergoed idee! ik heb het toegepast, bedankt 💯
