### ISSUE TITLE
Witregels

### ISSUE THREAD

**Issue by Maaike0904** [r20222/server-side-rendering#5]
https://github.com/r20222/server-side-rendering/blob/9e8dbf52d5d82cf0170d98e7bf6ddc7f95c733c6/public/style.css#L21-L23
Je zou hierboven en onder witregels kunnen toevoegen voor meer overzicht

**Comment by r20222** [comment]
Ik heb witruimtes gemaakt tussen elk verschillende onderdeel zoals nav of article. :)
